FROM ghcr.io/uliegecsm/amd-comgr-helpers/amd-comgr-helpers

# Installing gpg and gnupg2 allows the container to use GPG keys to sign commits.
# See also:
#   - https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials
RUN apt-helpers install-packages --update --clean --packages gpg gnupg2
